title: "Homelab Dashboard"

services:
  - id: qnap
    name: QNAP Dashboard
    url: http://happynas.org:8080
    local_url: http://10.10.10.30:8080
    description: QNAP NAS Admin dashboard
    summary: |
      ## QNAP Dashboard

      QNAP TS-223 admin dashboard 

      **Credentials**
      - Username: nastar
      - Password: sD.y4F,707@+UG,
    category: Storage
    icon: qnap
    status: operating

  - id: adguard-home
    name: AdGuard Home
    url: http://happynas.org:8080
    local_url: http://10.10.10.200
    description: Network-wide DNS ad blocker
    summary: |
      ## AdGuard Home

      - Admin Username: adguard
      - Admin Password: =0hTTOTx4U7M
    category: Network
    icon: adguard-home
    status: operating

  - id: proxmox
    name: Proxmox
    url: http://proxmox.tailebe625.ts.net:8006
    local_url: http://10.10.10.10:8006
    description: This home network proxmox cluster
    summary: |
      ## This home proxmox cluster

      - Username:  root
      - Password: Asenproxmox$1
    category: Infrastructure
    icon: proxmox
    status: operating

  - id: homelab-dashboard
    name: Homelab Dashboard
    url: http://homelab.db
    local_url: http://10.10.10.16
    description: This dashboard
    summary: |
      ## Homelab Dashboard

      A catalog of all services running in this Proxmox cluster. Edit via the Admin panel or directly in `config/services.yaml`.
    category: Infrastructure
    icon: home-assistant
    status: in-development
  
  - id: frappe-hr
    name: Frappe HRIS
    url: http://frappe.smw
    local_url: http://10.10.10.17
    description: Frappe HRIS clone
    summary: |
      ## Github 
      Forked from https://github.com/frappe/hrms#

      ## How to use
      User guide / Platform Introduction: https://docs.frappe.io/hr/introduction

      ## Credentials:
      
      * Username: Administrator
      * Password: admin

    category: SMW
    icon: "frappe-hr"
    status: in-development
  
  - id: semart-hris
    name: Semart HRIS
    url: http://semarthris.smw
    local_url: http://10.10.10.18
    description: Semart HRIS clone
    summary: |
      ## Github 
      Forked from https://github.com/KejawenLab/SemartHris
    category: SMW
    icon: "frappe-erpnext"
    status: in-development

  - id: personalab
    name: Persona Lab
    url: http://personalabs.org
    local_url: http://10.10.10.15
    description: Persona Lab
    summary: |
      ## Persona Lab

      in progress
    category: Personal
    icon: langflow
    status: in-development
